version: "3.0"

services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432

  migrations:
    build:
      context: .
      dockerfile: migrations.dockerfile
    environment:
      - DOMAIN=localhost
      - BACKEND_CORS_ORIGINS="http://localhost,http://localhost:5173,https://localhost,https://localhost:5173,http://localhost.tiangolo.com"
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changethis
    depends_on:
      - db

  backend:
    restart: always
    depends_on:
      - db
      - migrations
    env_file:
      - .env
    environment:
      - DOMAIN=localhost
      - BACKEND_CORS_ORIGINS="http://localhost,http://localhost:5173,https://localhost,https://localhost:5173,http://localhost.tiangolo.com"
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changethis

    build:
      context: ./backend
    
    ports:
      - 8080:8080

  frontend:  
    restart: always
    build:
      context: ./frontend
    ports:
      - 5173:5173


  redis:
    image: redis:7.2.1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redis-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=2

volumes:
  redis_data:



