"""Change base model

Revision ID: 4db0a0c30ab6
Revises: b3f95341cba0
Create Date: 2024-03-31 13:09:25.057163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db0a0c30ab6'
down_revision: Union[str, None] = 'b3f95341cba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tg_channels_chat_id_key', 'tg_channels', type_='unique')
    op.drop_constraint('tg_channels_username_key', 'tg_channels', type_='unique')
    op.create_unique_constraint(op.f('uq_tg_channels_chat_id'), 'tg_channels', ['chat_id'])
    op.create_unique_constraint(op.f('uq_tg_channels_username'), 'tg_channels', ['username'])
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_telegram_id'), 'users', ['telegram_id'])
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_telegram_id'), 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    op.drop_constraint(op.f('uq_tg_channels_username'), 'tg_channels', type_='unique')
    op.drop_constraint(op.f('uq_tg_channels_chat_id'), 'tg_channels', type_='unique')
    op.create_unique_constraint('tg_channels_username_key', 'tg_channels', ['username'])
    op.create_unique_constraint('tg_channels_chat_id_key', 'tg_channels', ['chat_id'])
    # ### end Alembic commands ###
