"""Add mappers

Revision ID: 980d479e7844
Revises: 4db0a0c30ab6
Create Date: 2024-03-31 13:20:15.926562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '980d479e7844'
down_revision: Union[str, None] = '4db0a0c30ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_channel_posts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tg_channel_posts', 'tg_channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tg_channel_posts', 'publish_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tg_channel_posts', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tg_channel_posts', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tg_channels', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vk_channel_posts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vk_channel_posts', 'vk_channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vk_channel_posts', 'publish_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vk_channel_posts', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('vk_channel_posts', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vk_channels', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vk_channels', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vk_channels', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vk_channels', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vk_channel_posts', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vk_channel_posts', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('vk_channel_posts', 'publish_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vk_channel_posts', 'vk_channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vk_channel_posts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tg_channels', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tg_channel_posts', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tg_channel_posts', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tg_channel_posts', 'publish_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tg_channel_posts', 'tg_channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tg_channel_posts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
